name: altaqwaa
title: altaqwaa | Islamic desktop application
adopt-info: altaqwaa
summary: altaqwaa | Islamic desktop application
description: >
  مميزات التطبيق

  * القرآن الكريم كتابة و صوت
  * حصن المسلم
  * أسماء الله الحسنى ومعانيها
  * أذكار الصباح
  * أذكار المساء
  * أذكار النوم
  * أذكار الطعام
  * أذكار الصلاة
  * تسابيح
  * مواقيت الصلاة
  * إشعار صوت وكتابة بدخول وقت الصلاة
  * إشعارات أذكار متنوعة
  * إشعارات صوت أذكار الصباح والمساء
  * إمكانية إيقاف وتفعيل الإشعارات
icon: build/icons/icon.png
architectures:
  - build-on: amd64
    run-on: amd64
  - build-on: arm64
    run-on: arm64
license: MIT License

grade: stable
confinement: strict
base: core20

apps:
  altaqwaa:
    command: ./app/altaqwaa --no-sandbox
    extensions:
      - gnome-3-38
    plugs:
      - home
      - browser-support
      - network
      - adb-support
      - raw-usb

parts:
  altaqwaa:
    plugin: dump
    source: .
    build-snaps:
      - node/16/stable
    build-packages:
      - npm
      - libgconf-2-4
    stage-packages:
      - libusb-1.0-0
      - libnss3
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version `cat $SNAPCRAFT_PROJECT_DIR/package.json | grep version | sed s/'  \"version\": \"'//g | sed s/'\",'//g`
    override-build: |
      echo "Running override-build script"
      http_proxy="${http_proxy:-}"
      https_proxy="${https_proxy:-}"
      echo "https_proxy: " $https_proxy
      echo "http_proxy: " $http_proxy
      echo "updating npm" && npm install npm@latest -g
      echo "installing dependencies" && npx cross-env ELECTRON_GET_USE_PROXY=true GLOBAL_AGENT_HTTPS_PROXY=$https_proxy npm install || sleep 15 && npx cross-env ELECTRON_GET_USE_PROXY=true GLOBAL_AGENT_HTTPS_PROXY=$https_proxy npm install
      echo "rollup" && npm run build
      [ `uname -m` == "aarch64" ] && UBPORTS_ARCH=arm64 || UBPORTS_ARCH=x64
      [ `uname -m` == "aarch64" ] && UBPORTS_DISTDIR=linux-arm64-unpacked || UBPORTS_DISTDIR=linux-unpacked
      ELECTRON_GET_USE_PROXY=true
      GLOBAL_AGENT_HTTPS_PROXY=$https_proxy
      ./build.js -o 'linux' -p 'dir' -a $UBPORTS_ARCH -e '{"package": "snap"}'
      mkdir -p $SNAPCRAFT_PART_INSTALL/app
      rm -rf $SNAPCRAFT_PART_INSTALL/app/*
      mv dist/$UBPORTS_DISTDIR/* $SNAPCRAFT_PART_INSTALL/app
    prime:
      - -node_modules
      - -lib/node_modules
      - -**/arm/**
      - -**/arm64/**
      - -**/ia32/**