name: altaqwaa
title: altaqwaa | Islamic desktop application
adopt-info: altaqwaa
summary: altaqwaa | Islamic desktop application
description: >
  مميزات التطبيق

  * القرآن الكريم كتابة و صوت
  * حصن المسلم
  * أسماء الله الحسنى ومعانيها
  * أذكار الصباح
  * أذكار المساء
  * أذكار النوم
  * أذكار الطعام
  * أذكار الصلاة
  * تسابيح
  * مواقيت الصلاة
  * إشعار صوت وكتابة بدخول وقت الصلاة
  * إشعارات أذكار متنوعة
  * إشعارات صوت أذكار الصباح والمساء
  * إمكانية إيقاف وتفعيل الإشعارات
icon: build/icons/icon.png
license: MIT License
grade: stable
confinement: strict

apps:
  altaqwaa:
    command: ./app/altaqwaa --no-sandbox
    extensions:
      - gnome-3-38
    plugs:
      - home
      - browser-support
      - network
      - adb-support
      - raw-usb

parts:
  altaqwaa:
    plugin: nil
    source: https://github.com/rn0x/Altaqwaa-Islamic-Desktop-Application.git
    override-build: |
        npm install electron electron-packager
        npx electron-packager . --overwrite --platform=linux --output=release-build --prune=true
        cp -rv ./altaqwaa-linux-* $SNAPCRAFT_PART_INSTALL/altaqwaa
    build-snaps:
    - node/14/stable
    build-packages:
    - unzip
    stage-packages:
    - libnss3
    - libnspr4