name: altaqwaa
title: altaqwaa | Islamic desktop application
adopt-info: altaqwaa
summary: altaqwaa | Islamic desktop application
description: >
  مميزات التطبيق

  * القرآن الكريم كتابة و صوت
  * حصن المسلم
  * أسماء الله الحسنى ومعانيها
  * أذكار الصباح
  * أذكار المساء
  * أذكار النوم
  * أذكار الطعام
  * أذكار الصلاة
  * تسابيح
  * مواقيت الصلاة
  * إشعار صوت وكتابة بدخول وقت الصلاة
  * إشعارات أذكار متنوعة
  * إشعارات صوت أذكار الصباح والمساء
  * إمكانية إيقاف وتفعيل الإشعارات
icon: build/icons/icon.png
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

license: MIT License
grade: stable
confinement: strict

apps:
  altaqwaa:
    command: ./app/altaqwaa --no-sandbox
    extensions:
      - gnome-3-38
    plugs:
      - home
      - browser-support
      - network
      - adb-support
      - raw-usb

parts:
  altaqwaa:
    plugin: dump
    source: https://github.com/rn0x/Altaqwaa-Islamic-Desktop-Application.git
    build-snaps:
      - node/16/stable
    build-packages:
      - npm
      - libgconf-2-4
    stage-packages:
      - libnspr4
      - libusb-1.0-0
      - libnss3
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version `cat $SNAPCRAFT_PROJECT_DIR/package.json | grep version | sed s/'  \"version\": \"'//g | sed s/'\",'//g`
     override-build: |
      set +u # core20 base does not allow unbound variables !
      # workaround for build.snapcraft.io builds
      # https://bugs.launchpad.net/bugs/1886861
      if [ -n "$http_proxy" ]; then
        export ELECTRON_GET_USE_PROXY=1
        export GLOBAL_AGENT_HTTP_PROXY="${http_proxy}"
        export GLOBAL_AGENT_HTTPS_PROXY="${http_proxy}"
      fi
      npm install --unsafe-perm true electron-packager
      cp $SNAPCRAFT_PROJECT_DIR/main.js .
      electron-packager . --overwrite --platform=linux \
          --output=release-build --prune=true
      cp -a ./electron-quick-start-linux-* $SNAPCRAFT_PART_INSTALL/altaqwaa
    prime:
      - -node_modules
      - -lib/node_modules
      - -**/arm/**
      - -**/arm64/**
      - -**/ia32/**